name: Deploy React to GitHub Pages

on:
  push:
    branches: [ "main" ]  # troque se usar outro branch

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node (with npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          # APONTE para o lockfile dentro da subpasta do projeto
          cache-dependency-path: personal-portfolio/package-lock.json

      - name: Install deps (client)
        working-directory: personal-portfolio
        run: npm ci

      - name: Build (client)
        working-directory: personal-portfolio
        run: npm run build

      - name: Disable Jekyll
        run: touch personal-portfolio/build/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: personal-portfolio/build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
